# Generated by Django 3.0.5 on 2020-10-04 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.TextField(choices=[('NEW', 'Новая'), ('PLANNED', 'Запланированная'), ('IN PROGRESS', 'В работе'), ('COMPLETED', 'Завершенная')], default='NEW')),
                ('complete_date', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата завершения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
