# Generated by Django 3.0.5 on 2020-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201004_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('new', 'новая'), ('planned', 'запланированная'), ('performing', 'в работе'), ('completed', 'завершенная')], default='new'),
        ),
    ]
